import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['packages/*/src/**/*.test.{ts,tsx}', 'test/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      include: ['packages/core/src/**', 'packages/react/src/**'],
      exclude: [
        '**/*.test.{ts,tsx}',
        '**/index.ts',
        '**/*.d.ts',
        // pure type-only modules: no executable statements for v8 to instrument
        'packages/core/src/engine/Engine.ts',
        'packages/core/src/interaction/controller/InteractionController.ts',
        'packages/core/src/model/SerializedState.ts',
        'packages/core/src/solver/search/SearchProblem.ts',
        'packages/core/src/shared/unions/ValueOf.ts',
        'packages/core/src/shared/unions/HandlerMap.ts',
        'packages/core/src/shared/geometry/Point.ts',
        'packages/core/src/model/WidgetInstance.ts',
        'packages/core/src/model/Board.ts',
        'packages/core/src/model/LayoutTile.ts',
        'packages/core/src/ops/Op.ts',
        'packages/core/src/ops/OpHandler.ts',
        'packages/core/src/ops/outcome/Rejection.ts',
        'packages/core/src/ops/outcome/Change.ts',
        'packages/core/src/ops/outcome/Applied.ts',
        'packages/core/src/reflow/Page.ts',
        'packages/core/src/reflow/ReflowChange.ts',
        'packages/core/src/reflow/ReflowPlacementInput.ts',
        'packages/core/src/reflow/ReflowResult.ts',
        'packages/core/src/interaction/machine/StepResult.ts',
        'packages/core/src/interaction/StepContext.ts',
        'packages/core/src/interaction/events/MessageParams.ts',
        'packages/core/src/interaction/events/Effect.ts',
        'packages/core/src/interaction/events/InteractionEvent.ts',
        'packages/core/src/interaction/state/InteractionState.ts',
        'packages/core/src/interaction/state/InteractionOptions.ts',
        'packages/core/src/interaction/controller/PointerSnapshot.ts',
        'packages/core/src/engine/EngineContext.ts',
        'packages/core/src/engine/EngineConfig.ts',
        'packages/core/src/issues/Issue.ts',
        'packages/core/src/repair/Repaired.ts',
        'packages/core/src/solver/search/TraceFn.ts',
        'packages/core/src/solver/search/SearchOutcome.ts',
        'packages/core/src/solver/grid/Relocation.ts',
        'packages/core/src/solver/grid/SolverOptions.ts',
        'packages/core/src/solver/grid/RelocationInput.ts',
        'packages/core/src/solver/grid/search/RelocationBoard.ts',
        'packages/core/src/solver/grid/search/RelocationState.ts',
        'packages/react/src/provider/ChangeMeta.ts',
        'packages/react/src/provider/config/AtInput.ts',
        'packages/react/src/shared/size/SizeInput.ts',
        'packages/react/src/provider/config/BoardsConfig.ts',
        'packages/react/src/provider/config/GridBreakpoint.ts',
        'packages/react/src/provider/config/ResolvedBreakpoint.ts',
        'packages/react/src/widget/WidgetProps.ts',
        'packages/react/src/widget/WidgetManifest.ts',
      ],
      reporter: ['text', 'json-summary', 'html'],
      thresholds: {
        'packages/core/src/**': { lines: 99, branches: 95, functions: 98 },
        'packages/react/src/**': { lines: 96, branches: 89, functions: 92 },
      },
    },
  },
});
